### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by swilc** [ShaneMcC/beeps#15]
Is this copyrighted? Could I use the code in a YouTube video?

**Comment by Crumpleboi** [comment]
I would be highly surprised if it was. I am not the creator of this
collection but I can tell you that CGNU.sh was made by me (copied from the
Mascot SBmail episode of Homestar runner). I would assume it's fine to use
but ask ShaneMcC first!

**Comment by ShaneMcC** [comment]
I'm not a copyright expert, but I've intentionally not put a `LICENSE` file or anything here because I don't know. I *personally* don't care if you do or not, but what I think doesn't really matter here.

Most of the files were either found somewhere online (comments in headers as applicable) or contributed here by others. But given that most of them were probably just converted/format-shifted from some other wav/midi format - I believe the copyright stays with the author of the original source file not the converted file.

**Comment by swilc** [comment]
Thank you!
